### users index
GET http://localhost:3000/users.json

### user show

Get http://localhost:3000/users/4.json

### user create

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Jim",
  "address": "24 W bird st"
}

### BOOKING INDEX
GET http://localhost:3000/bookings

### BOOKING SHOW

GET http://localhost:3000/bookings/1

### BOOKING CREATE

POST http://localhost:3000/bookings
Content-Type: application/json

{
  "user_id": 4,
  "clown_id": 1
}

### CLOWNS INDEX
GET http://localhost:3000/clowns

